param(
    [string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot)
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$resolvedRoot = [System.IO.Path]::GetFullPath($ProjectRoot)
$sourcePath = Join-Path $resolvedRoot 'src-tauri\target\release\WebView2Loader.dll'
$runtimeRoot = Join-Path $resolvedRoot 'packaging\runtime\root'
$targetPath = Join-Path $runtimeRoot 'WebView2Loader.dll'
$stagingPath = "$targetPath.staging"

if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
    throw "WebView2Loader.dll was not generated by the Rust build: $sourcePath"
}

$sourceFile = Get-Item -LiteralPath $sourcePath
if ($sourceFile.Length -le 0) {
    throw "Generated WebView2Loader.dll is empty: $sourcePath"
}

New-Item -ItemType Directory -Path $runtimeRoot -Force | Out-Null
if (Test-Path -LiteralPath $stagingPath) {
    Remove-Item -LiteralPath $stagingPath -Force
}

Copy-Item -LiteralPath $sourcePath -Destination $stagingPath -Force
$sourceHash = (Get-FileHash -LiteralPath $sourcePath -Algorithm SHA256).Hash
$stagingHash = (Get-FileHash -LiteralPath $stagingPath -Algorithm SHA256).Hash
if ($sourceHash -ne $stagingHash) {
    throw 'Staged WebView2Loader.dll failed the SHA-256 integrity check.'
}

Move-Item -LiteralPath $stagingPath -Destination $targetPath -Force
$targetHash = (Get-FileHash -LiteralPath $targetPath -Algorithm SHA256).Hash
if ($sourceHash -ne $targetHash) {
    throw 'Published WebView2Loader.dll failed the SHA-256 integrity check.'
}

Write-Host "Staged WebView2Loader.dll ($($sourceFile.Length) bytes)."
